POST http://192.168.43.79:4000/api/v1/admin/register/f0zSH0PEif3HODVaiKyn HTTP/1.1
content-Type: application/json

{
       "username" : "franchisehubadmin0",
       "password" : "nACr8DyipJRKtVFu"
}

###

POST http://localhost:4000/api/v1/admin/login HTTP/1.1
content-Type: application/json

{
       "username" : "fhadmin0",
       "password" : "nACr8DyipJRKtVFu"
}